local obfuscation = {
    a = 'aHiFlDllgK',
    A = 'DSAasDdAS',
    b = 'AFASFAFS',
    B = 'DASDASDAS',
    c = 'dASDASaSDaSD',
    C = 'dASaSDaSDasddasaSD',
    d = 'das',
    D = 'sdAASDADSdas',
    e = 'DSAADS',
    E = 'DSAaSDADSaSDADSaSDASD',
    f = 'ASDASD',
    F = 'sadASDASD',
    g = 'dsaASDASDdasASDasdadSASDadS',
    G = 'asdsdaASDdsAdsadsasdASADsdAdsAasd',
    h = 'sdasdADASsdAsdaasDsadsADASDsadASDASD',
    H = 'sdaasDdSAdasasdasdASDASDasdsad',
    i = 'dasasddASSDAdsaasdASDdASsdAASD',
    I = 'asdASDasddasadSasDasdasdaSD',
    j = 'adSASDsdAasdasdasdasdaSD',
    J = 'sadsdasaDdassda',
    k = 'asdASDASDasddASasd',
    K = 'dasASDadSdasdsaadS',
    l = 'sdaasdasdadssdadsa',
    L = 'asdasdasddasasdasd',
    m = 'asddASASDdasasdasddasadS',
    M = 'asdasdasdasdasdasddsasdaasdasdadsasda',
    n = 'asdasddasdassaddsasadasddasdsasda',
    N = 'sadasddasasddasasdsdaasd',
    o = 'sdasdaDASdsAsADdasdasdasdassda',
    O = 'ECWQECQWECQWeqwcecQWeQWCewQCeWQC',
    p = 'weCQecWQecWQ',
    P = 'eQWCEWQCeQWCeWQC',
    q = 'QWECeQWC',
    Q = 'eqwcEQWCEWQCeQWC',
    r = 'EQWCEQWCewcQecwqewcQ',
    R = 'QWECECWQEQWCWEQCEQWCEQWCeQWCEQWCEQWC',
    s = 'qewCeQWCeQWCeQWCeqwceqwC',
    S = 'ewqcqweceqwceqwceqwcqwec',
    t = 'eCQWECQEQCWeQWCeWQCEQWCewqc',
    T = 'ECQWEQWCeWQCeWQCeWCQeWQCewQCewQCeqwCewqC',
    u = 'eqwcEWCQEWQCeQWCWEQCewQCewQCeqwCewQCewQC',
    U = 'EQTCTECQQETCQETCQETCTQECetqcetcQTQECetqCt',
    v = 'tecqtqecqtecqtec',
    V = 'etqcetqctqectqectqecteqc',
    w = 'teqcqtecqtecqtecqetctecqectq',
    W = 'etcqtcqetqecteqcqectqetctqectqec',
    x = 'teqcetqcetqcteqcetqcetqcetqcqetctqecteqc',
    X = 'qectqetcqetcetqcetqceqtcqectetqctqecetcqetcq',
    y = 'tqecqetcqetcteqcetqcetqctqectqectqectqectqecteqc',
    Y = 'etqcetqcteqcteqcteqctqectqecteqcteqcteqtqetqectqectqec',
    z = 'etqctqecqetcteqcetqcetqcteqctecqetqcteqcteqctqectqecteqct',
    Z = 'tecqtecqqteceqtctqectctttqcqc',
    ['1'] = 'dsacdascdascdascdascdascdascdsac',
    ['2'] = 'dascdascsdacdsacdsacDASCDASC',
    ['3'] = 'ADSCDASCDASCdasCsdAC',
    ['4'] = 'SADCdASCdASCdASCdSACdSA',
    ['5'] = 'DACSCASdACSdACS',
    ['6'] = 'DACSdCASdASCdCASdcSA',
    ['7'] = 'DASCDACDASCdSACdSACdSAC',
    ['8'] = 'dASCDACSdASCDASCDSAC',
    ['9'] = 'dASCdASCdASCdSAC',
    ['0'] = 'dscaDSACADSCDSACdSACdSAC',
    ['+'] = 'DSCADSCADSACDASCdSACADCS',
    ['-'] = 'DACS',
    ['/'] = 'ADSC',
    ['*'] = 'dacs',
    ['%'] = 'dasc',
    ['&'] = 'eQRCQERCRQECQRECQERCrqeC',
    ['('] = 'QERCQERCQERCQERCrQECQERC',
    [')'] = 'QRCWrcqrECWerCqWRCrqeRCWqrWEC',
    ['.'] = 'pkpIKOCpoikCPKOCPOKopk',
    ['"'] = 'nkdasckjnasdckjndasckjn',
    ["'"] = 'adcsdcASLKMlkmDASCkmlDACS',
    ['['] = 'mmkdACSlkmACDSlkmaDSCLkmdaSCLKM',
    ['{'] = 'kmdasckmldascklmsdakmlcdkmslacsdkmlac',
    [']'] = 'dcsakmldasclkmsdaclkmlkmasdc',
    ['}'] = 'opikdpsckaspdcoksdacpoksadcpok',
    ['='] = 'ojaciepierdole',
    ['<'] = 'ociechujpizgniety',
    ['>'] = 'marianpazdzioch',
    ['~'] = 'jebactoskruwialeforum',
    ['_'] = 'dareqplaystociapekspierdolony',
    ['!'] = 'adriannowakzalnotokoks',
    ['@'] = 'jebacrobloxaiexploitingcommunity',
    ['#'] = 'wyruchanywcipke',
    ['$'] = 'ruchaniejestostre',
    ['%'] = 'alebymciewyruchal',
    ['^'] = 'ruchanybedzieszjutro',
    [' '] = 'spierdalajkutasiarzu',
    ['.'] = 'motherbitch',
    [','] = 'saymynameimheisenberg',
    ['\n'] = 'HAHAHAMANIMDEAD',
    grave = 'kutasiarsko',
    backslash = 'kasztanowy'
}

local random_junk = {
    'aHkkiFlDllgK',
    'DSAkkasDdAS',
    'AFAkkkSFAFS',
    'DASkkkDASDAS',
    'dASDAkkkSaSDaSD',
    'dASaSDaSkkDasddasaSD',
    'daks',
    'sdAASkDADSdas',
    'DSkAADS',
    'DSAakSDADSaSDADSaSDASD',
    'ASDkASD',
    'sadkkkASDASD',
    'dsaASkkDASDdasASDasdadSASDadS',
    'asdskkdaASDdsAdsadsasdASADsdAdsAasd',
    'sdasdAkkDASsdAsdaasDsadsADASDsadASDASD',
    'sdaasDdSkkAdasasdasdASDASDasdsad',
    'dasaskkkddASSDAdsaasdASDdASsdAASD',
    'asdASkkDasddasadSasDasdasdaSD',
    'adSASkkkDsdAasdasdasdasdaSD',
    'sadsdaskkkaDdassda',
    'asdASDAkkkSDasddASasd',
    'dasASkkkDadSdasdsaadS',
    'sdaakkksdasdadssdadsa',
    'asdaskkkdasddasasdasd',
    'asddAkkkSASDdasasdasddasadS',
    'asdaskkkdasdasdasdasddsasdaasdasdadsasda',
    'asdasddakkksdassaddsasadasddasdsasda',
    'sadasddasakkksddasasdsdaasd',
    'sdasdaDAkkkSdsAsADdasdasdasdassda',
    'ECWQECQWkkECQWeqwcecQWeQWCewQCeWQC',
    'ECQWEQWCeWQCesdfgWQCeWCQeWQCewQCewQCeqwCewqC',
    'eqwcEWCQEWQCeQWCsdWEQCewQCewQCeqwCewQCewQC',
    'EQTCTECQQETCQEsdTCQETCTQECetqcetcQTQECetqCt',
    'tecqtqecqtecsdqtec',
    'etqcetqctqesdctqectqecteqc',
    'teqcqtecqtedcqtecqetctecqectq',
    'etcqtcqefftqecteqcqectqetctqectqec',
    'etqctqecqdetcteqcetqcetqcteqctecqetqcteqcteqctqectqecteqct',
    'pkpIKOCpoikCPasdKOCPOKopk',
    'ociechujpizgasdasdasdniety',
    'jebaniewdupe',
    'mysliszzecostuznajdzies',
    'jebacciewdupepizdoklesszczu',
    'wyruchamciemocnoazulx',
    'jebac3dsboy08',
    'psutonajlepszyobfuscator',
    'acediatosmiec',
    'twojastarajestjebana',
    'darunotozjeb',
    'dareqplaystozjeb',
    'proobfuscatorlepszynizluraph',
    'takpolskiobfusactor',
    'jestesjebanywdupkeitobardzoostro',
    'mysliszzecostutajznajdziesztypedalyobsranyzvermillion',
    'tyskidziepierdolony',
    'cexczysextojestpytanie',
    'fifasiedemnascie',
    'fifaosiemnascie',
    'fifadziewietnascie',
    'legomarvelsuperheroes',
    'pepsijestdobraipijejacodzienniepoczterylitry',
    'emptinessjestgruby',
    'ririrhcijestgruby'
}

return function(script)
    local obfuscated = ''
    for i = 1, 2000 do 
        obfuscated = obfuscated .. random_junk[math.random(1, #random_junk)] .. ' '
    end 
    for i = 1, #script do 
        if string.sub(script, i, i) == [[\]] then 
            obfuscated = obfuscated .. obfuscation.backslash .. ' '
        elseif string.sub(script, i, i) == [[*]] then 
            obfuscated = obfuscated .. obfuscation.grave .. ' '
        else 
            obfuscated = obfuscated .. obfuscation[string.sub(script, i, i)] .. ' '
        end 
    end 
    for i = 1, 2000 do 
        obfuscated = obfuscated .. random_junk[math.random(1, #random_junk)]
    end 
    local copy = "local _,run = {['obfuscated with hashfuscator v1.0.2.1']=nil},\nloadstring(game:HttpGet('https://raw.githubusercontent.com/zuhnosu/test/main/test.lua'))()([[%s]])()"
    copy = copy:format('\n' .. obfuscated .. '\n')
    setclipboard(copy)
    return copy
end
